# Generated by Django 4.0.2 on 2022-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='contact_number',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
