# Generated by Django 4.0.2 on 2022-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='contact_number',
            field=models.CharField(max_length=25),
        ),
    ]
