# Generated by Django 4.0.2 on 2022-03-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='bye',
            new_name='buy',
        ),
    ]
