# Generated by Django 4.0.2 on 2022-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_bye_rate_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.DecimalField(decimal_places=0, max_digits=25)),
            ],
        ),
    ]
