# Generated by Django 4.0.2 on 2022-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rate_base_type_alter_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='contact_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
