# Generated by Django 4.0.2 on 2022-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_source_contact_number_alter_source_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='contact_number',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(max_length=100),
        ),
    ]
